services:
  node:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "${EXPRESS_PORT:-3030}:3030"
    command: >
      sh -c 'if [ "$NODE_ENV" = "prod" ]; then exec npm start; else exec npm run dev; fi'
    networks:
      - app
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER:-tictac}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE:-application}"
    volumes:
      - ./storage/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app
networks:
  app:
