services:
  node:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "${EXPRESS_PORT:-3030}:3030"
    command: "npm start"
    networks:
      - app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER:-mongo}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD:-mongo}"
    volumes:
      - ./storage/mongodb:/data/db
    networks:
      - app
networks:
  app:
